name: version jar
on:
  push:
    tags:
      - "v*"
    branches:
      - 'master'
permissions:
  contents: write
    
jobs:
  build-jar-job:
    name: 'Version Jar'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Run the Ant ci target
        run: ant -noinput -buildfile build.xml dist
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/dist/jbench.jar
          asset_name: jbench.jar
          asset_content_type: application/zip
          tag: ${{ github.ref }}
          overwrite: true
