name: version bin
on:
  push:
    tags:
      - "v*"
    branches:
      - 'master'
permissions:
  contents: write
              
jobs:
  build-bin-job:
    name: 'Version Bin'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Run Graalvm to generate bin
        run: ./src/script/build_github.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/bin/jbench
          asset_name: jbench
          asset_content_type: application/octet-stream
          tag: ${{ github.ref }}
          overwrite: true
