name: version bin
on:
  push:
    tags:
      - "v*"
    branches:
      - 'master'
jobs:
  build-bin-job:
    name: 'Version Bin'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Run the Ant ci target
        run: ./src/script/build_io.sh
      - uses: actions/upload-artifact@v3
        with:
          name: jbench
          path: target/bin/jbench