name: version jar
on:
  push:
    tags:
      - "vj*"
    branches:
      - 'master'

jobs:
  build-jar-job:
    name: 'Version Jar'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Run the Ant ci target
        run: ant -noinput -buildfile build.xml dist
      - uses: actions/upload-artifact@v3
        with:
          name: jbench.jar
          path: target/dist/jbench.jar