name: version jar
on:
  push:
    tags:
      - "v*"
    branches:
      - 'master'

jobs:
  build-jar-job:
    name: 'Version Jar'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Run the Ant ci target
        run: ant -noinput -buildfile build.xml dist
      - name: Upload Release Asset
          id: upload-release-asset 
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }} 
            asset_path: target/dist/jbench.jar
            asset_name: jbench.jar
            asset_content_type: application/ZIP
